### ISSUE TITLE
任务节点事件监听回调

### ISSUE THREAD

**Issue by lensun1** [GoldSubmarine/workflow-bpmn-modeler#1]
暂无任务节点事件监听回调

**Comment by GoldSubmarine** [comment]
是没有提供，我想不到要添加监听回调的场景，因为它就是画个图，导出xml用来部署啊，能说一下你的场景吗？

**Comment by lensun1** [comment]
例如，请假流程审批结束，需要在XML结束节点配置回调，更新请假相关报表的状态。

**Comment by lensun1** [comment]
还有一个选择用户那个地方用下拉框不适用，最好可以根据组织机构去筛选用户。

**Comment by GoldSubmarine** [comment]
哦，我理解成：添加一个任务节点时，vue 去 emit 一个事件了😅

目前是没有提供  监听类  配置，上次看了下flowable官方的设计器， 监听类  配置的参数有点多，没看明白每个参数的含义。

目前我这边是自己实现了 `org.flowable.common.engine.api.delegate.event.FlowableEventListener` 接口，它可以捕获到所有的 flowable 事件，然后自己封装一层，变成自己定义的事件，用 `ApplicationContext` 抛出即可。

这周有空再看一下 监听类的配置。

**Comment by GoldSubmarine** [comment]
> 还有一个选择用户那个地方用下拉框不适用，最好可以根据组织机构去筛选用户。

group和user不一定强关联的，且已提供搜索功能，用起来应该不麻烦

**Comment by lensun1** [comment]
XML流程是否可以增加预览只读模式



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "GoldSubmarine"<notifications@github.com&gt;; 
发送时间: 2020年8月24日(星期一) 下午5:27
收件人: "GoldSubmarine/workflow-bpmn-modeler"<workflow-bpmn-modeler@noreply.github.com&gt;; 
抄送: "Len"<sldodo@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [GoldSubmarine/workflow-bpmn-modeler] 任务节点事件监听回调 (#1)





  
还有一个选择用户那个地方用下拉框不适用，最好可以根据组织机构去筛选用户。
  
group和user不一定强关联的，且已提供搜索功能，用起来应该不麻烦

**Comment by lensun1** [comment]
一般都是需要集成到第三方系统，最好顶部操作按钮栏目可以提供扩展按钮插槽，例如“保存发布”



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "GoldSubmarine"<notifications@github.com&gt;; 
发送时间: 2020年8月24日(星期一) 下午5:27
收件人: "GoldSubmarine/workflow-bpmn-modeler"<workflow-bpmn-modeler@noreply.github.com&gt;; 
抄送: "Len"<sldodo@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [GoldSubmarine/workflow-bpmn-modeler] 任务节点事件监听回调 (#1)





  
还有一个选择用户那个地方用下拉框不适用，最好可以根据组织机构去筛选用户。
  
group和user不一定强关联的，且已提供搜索功能，用起来应该不麻烦

**Comment by GoldSubmarine** [comment]
有计划支持，并且可以根据流程的状态，改变颜色用来区分哪些已经审批过，哪些没有审批

“保存发布”自己在组件外加一个按钮即可，我是用 dialog 弹窗的右下角，有个保存按钮

**Comment by lensun1** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "GoldSubmarine"<notifications@github.com&gt;; 
发送时间: 2020年8月24日(星期一) 晚上6:39
收件人: "GoldSubmarine/workflow-bpmn-modeler"<workflow-bpmn-modeler@noreply.github.com&gt;; 
抄送: "Len"<sldodo@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [GoldSubmarine/workflow-bpmn-modeler] 任务节点事件监听回调 (#1)





 
有计划支持，并且可以根据流程的状态，改变颜色用来区分哪些已经审批过，哪些没有审批
 
“保存发布”自己在组件外加一个按钮即可，我是用 dialog 弹窗的右下角，有个保存按钮
 
&mdash;

**Comment by GoldSubmarine** [comment]
v0.2.2 支持该功能
