### ISSUE TITLE
用户任务节点可以配置任务监听器么？

### ISSUE THREAD

**Issue by lwgCodePlus** [GoldSubmarine/workflow-bpmn-modeler#10]

**Comment by GoldSubmarine** [comment]
可以啊，demo上不是可以配的么

**Comment by lwgCodePlus** [comment]
那个是执行监听器吧

**Comment by lwgCodePlus** [comment]
能不能支持下这个功能，自己改了一天也没改出来

**Comment by GoldSubmarine** [comment]
执行监听器就是你需要的

**Comment by GoldSubmarine** [comment]
有问题可以加微信   x997462392

**Comment by GoldSubmarine** [comment]
这个地方的确有问题，执行监听器和任务监听器不一样，之前我理解错了，预计国庆期间发一版支持

**Comment by lwgCodePlus** [comment]
导入bpmn20.xml文件，用户任务节点执行监听器里面的数据不能回显

**Comment by GoldSubmarine** [comment]
功能还没实现，肯定不能回显，国庆发版后可以再试试。

而且有一点需要注意的是，一个功能可能有很多种不同的配置方法，比如多实例，flowable 文档中有 3 种配置方法，我实现了其中一种，所以其他流程器导出的xml，不一定能在我的设计器中回显数据。

**Comment by GoldSubmarine** [comment]
v0.2.3 已支持任务监听器，解决数据回显问题
