### ISSUE TITLE
节点id 和 节点名称等，会受到 _this.formData.userType 的影响？

### ISSUE THREAD

**Issue by teamemory** [GoldSubmarine/workflow-bpmn-modeler#16]
![image](https://user-images.githubusercontent.com/24648667/95648530-8b534200-0b0a-11eb-84be-3b44bf2d5794.png)

**Comment by teamemory** [comment]
如上图，发现注释掉 form 表单  show: _this.formData.userType  === '  '  这个属性，然后节点id 和节点名称等才能出现，这个什么原因了？

**Comment by GoldSubmarine** [comment]
你是自己在改原码，然后按钮不显示了？

貌似我的demo上没有这个问题

**Comment by teamemory** [comment]
> 你是自己在改原码，然后按钮不显示了？
> 
> 貌似我的demo上没有这个问题

因为候选组，候选人等文字，我要根据我这边的需求进行改名字，所以我需要自定义一些东西。
然后我的做法是，我把package那个文件夹和Demo.vue 移到我的项目中，然后我安装了xcrud 和 bpmn-js npm包。
跑起来后的第一个问题是需要点击空白处才能加载右侧的Panel面板，我建议改成默认就显示流程分类和流程标识key的那个面板。
第二个问题是我点击某一个节点，然后人员类型能回显出来，但是节点id 节点名称无法回显；经过我调试，formData 也打印出来对应的字段了，但是没有回显上去。如果我把指定人员、候选人员、候选组的那个show属性注释掉或者_this.formData.userType === "candidateUsers" 等相关判断去掉，id 和name 就能回显出来。

烦请大佬，帮忙看一下是什么问题，导致这个回显有问题，是xcurd 的原因吗？ 还是什么原因

![image](https://user-images.githubusercontent.com/24648667/95648892-3664fb00-0b0d-11eb-96f9-a85ca2ed6110.png)

**Comment by GoldSubmarine** [comment]
问题一：同issue #8 ，这个有空支持，不影响使用

问题二：听你的描述貌似没有改动源码，id和name就没有回显，另外你的截图上，监听器的按钮也没有显示出来。看了下代码，id和name没有任何显隐控制，所以我猜测控制台是不是报错了？

另外你说    注释掉 form 表单 show: _this.formData.userType === ' ' 这个属性    指的是哪个文件的哪一行？

最后，我不知道你为何要自定义候选组，候选人等文字，这是flowable官方的术语，应该没有自定义的需求。

**Comment by teamemory** [comment]
![image](https://user-images.githubusercontent.com/24648667/95649694-5f878a80-0b11-11eb-8755-7ce548be8dcc.png)
![image](https://user-images.githubusercontent.com/24648667/95649709-6c0be300-0b11-11eb-8706-cb319d3c22c9.png)
我对比了一下，你的demo 和我放在我项目中打印出来的结果是一样的（xml 也是用的你的数据），但是我项目中的无法回显节点名称id以及任务监听器等内容。

show 属性位置如下，我把show注释掉就可以回显节点id 和节点名称（理论上不能注释掉）
![image](https://user-images.githubusercontent.com/24648667/95649798-fce2be80-0b11-11eb-9a97-53d4903bb1f9.png)

因为我们公司做工作流用户可选类型为 （所有用户，部门负责人，职务类型），而且所有用户和职务类型选择的时候还存在分页，不能直接用下拉框，所以得自定义一些内容。

**Comment by GoldSubmarine** [comment]
照理说这两个 show 和id、name没有任何关系，我不知道什么原因导致了这个问题。

如果出现特定需求，应该通过自己设计一套增删改查页面来支持，不应该直接通过定制流程设计器实现。

你的这个需求不需要自定义就能实现。

- 如果是所有用户，直接写一个变量就好了，而不是勾选所有的人。
- 如果是职务类型，说白了就是group或者角色，在flowable里这个叫候选组。
- 如果是部门负责人，应该也在流程图上写一个变量，然后让后端查询到发起人所在部门的负责人，将负责人id赋值到流程图上的变量即可。

![image](https://user-images.githubusercontent.com/22909744/95650150-3f0cff80-0b14-11eb-847b-dffc56e56bfa.png)

**Comment by GoldSubmarine** [comment]
好像 java 后端不是你负责，其实这都是后端的锅，不需要你来自定义设计器的。可以让后端搜索一下：通过修改流程实例变量让任务达到动态指定人员的效果。

**Comment by teamemory** [comment]
> 好像 java 后端不是你负责，其实这都是后端的锅，不需要你来自定义设计器的。可以让后端搜索一下：通过修改流程实例变量让任务达到动态指定人员的效果。

我平衡了一下，我自己用element 写表单呀，这样就能正常回显了，麻烦就麻烦点，多谢了

**Comment by GoldSubmarine** [comment]
ok
