### ISSUE TITLE
点击缩小按钮，实际却放大了

### ISSUE THREAD

**Issue by teamemory** [GoldSubmarine/workflow-bpmn-modeler#17]
点击缩小按钮，实际却放大了，如上bug

**Comment by GoldSubmarine** [comment]
我也发现了这个bug，但是貌似是bpmn.io 这个库的bug，通过鼠标缩放后，他没有把正确的缩放比例返回给我，导致点击按钮缩放时是对上次的比例进行缩放。

应该只有通过鼠标滚轮缩放后的那次按钮点击，才有这个问题，后续的放大缩小点击应该没有问题，这个等待bpmn.io升级解决
