### ISSUE TITLE
画模型时，图经常看不见，渲染不出来

### ISSUE THREAD

**Issue by yinzi2012** [GoldSubmarine/workflow-bpmn-modeler#18]
您好，画模型时，图经常看不见，渲染不出来。之前版本没这个问题，新版本有这个问题。

**Comment by teamemory** [comment]
我也发现了，chorme 86 版本以上就出现这个问题了，86以下的版本没问题。
![image](https://user-images.githubusercontent.com/24648667/97964773-43b39380-1df4-11eb-87b9-95ee38fb541d.png)

**Comment by teamemory** [comment]
![image](https://user-images.githubusercontent.com/24648667/98061479-e87eb100-1e86-11eb-873b-7f3d414aa200.png)
加了一段css , 解决了这个问题。

**Comment by yinzi2012** [comment]
真厉害，大神

**Comment by GoldSubmarine** [comment]
v0.2.5 修复
