### ISSUE TITLE
是否考虑使用原生的 elementui 封装右边的属性面板

### ISSUE THREAD

**Issue by zhuangjinming16** [GoldSubmarine/workflow-bpmn-modeler#19]
作者您好，首先谢谢您的 `workflow-bpmn-modeler` ，对我帮助很大，但是我想请问下是否会考虑出另外一个版本使用原生的 `elementui` 封装右边的属性面板，
因为我自己原前端项目用的是原生的 `elementui`，如果集成您现有的 `workflow-bpmn-modeler` ，使用的是 `xcrud` ，后续维护的话要遵循 `xcrud` 的规范，所以我想问下，是否可以出一版使用原生 `elementui` 封装右边的属性面板，可能受众面也会更广一些，感谢您的耐心阅读，谢谢。

**Comment by GoldSubmarine** [comment]
`xcrud` 是封装了 `elementui`，切换为原生工作量太大了，使用 `xcrud` 就是为了加快本库的开发

我是觉得不会出现需要定制本库的需求，应该只通过 npm 安装使用，另外等 `vue@3` 和 `element-plus` 成为标配后，本库也不会升级，到时候建议使用 iframe 方式部署，说到底，这只是一个程序员开发阶段通过拖拽生成 xml 使用的工具

**Comment by zhuangjinming16** [comment]
感谢您的回复，定制版的需求会很多的，不同行业不同场景对工作流的要求不同，您可以看一下，盘古BPM的demo（未开源），
[盘古BPM](http://vue.pangubpm.com/) （流程平台-流程辅助功能-模型管理-编辑），您的 `workflow-bpmn-modeler` 如果能出一个原生 `elementui` 的版本受众面会更广，很多人也会加入维护，包括我，当然 'xcurd' 也是不错的。

**Comment by GoldSubmarine** [comment]
> 不同行业不同场景对工作流的要求不同

的确是这样的，但是我更倾向于针对场景通过额外的表单和数据库表进行配置（参考jeecg），而不是自行扩展 flowable 的属性。从工作量上评估，通过额外表单也会更简单（让后端从 xml 中解析自定义数据是一件比较麻烦的事😂）

![image](https://user-images.githubusercontent.com/22909744/97068862-f407e780-15fd-11eb-9b0b-a732aa15a064.png)

比如盘古对任务分配人员时，提供了这些选项，我不觉得这是好的设计，从接口中看出它是在 xml 上自定义了很多非 flowable 的属性，这让 xml 失去了通用性。

这个库对标的是 flowable 官方的流程设计器，使用的术语也都是来自 flowable 官方文档。
