### ISSUE TITLE
左侧工具栏 UserTask 用户工具为啥没显示

### ISSUE THREAD

**Issue by clearself** [GoldSubmarine/workflow-bpmn-modeler#21]
左侧工具栏 UserTask 用户工具为啥没显示

**Comment by GoldSubmarine** [comment]
这个是 bpmn.io 这么设计的，我想这么设计的原因是：UserTask 并不比其他的 Task 特殊，所以应该是平起平坐的地位

你需要先拖拽出一个 task ，然后修改类型为 userTask

**Comment by clearself** [comment]
谢谢啊，从你的这个项目里我学到很多东西
