### ISSUE TITLE
关于组件的部分bug

### ISSUE THREAD

**Issue by Nuan-Yang** [GoldSubmarine/workflow-bpmn-modeler#22]
作者您好:
我最近在使用您的组件的时候发现了一些问题，现在描述给您，期待您尽快修复.
问题1：save()方法在返回的data中是通过getElement的第0个节点来返回流程id的，然而事实上第一个节点不一定是bpmn:process类型(起码我这个从其他地方生成的不是)所以建议获取的时候使用遍历查找bpmn:process 来返回数据。
问题2：扩展流程使用后，流程侧栏空白无法展示。（点击空白处也存在问题，看不到属性栏）。
期待您的回复及bug修复

**Comment by GoldSubmarine** [comment]
问题 1 的确是这样，信号和消息都是和 bpmn:process 并级的，这周修复一下

扩展流程目前的确不支持配置，这个要再看看了

**Comment by GoldSubmarine** [comment]
请问你的业务中有使用扩展流程吗？搜了一下flowable的文档，居然没有扩展流程的内容，只有子流程的相关内容。你是单纯发现拖拽出扩展流程后，面板失效，还是真实业务中有使用呢？

**Comment by Nuan-Yang** [comment]
> 请问你的业务中有使用扩展流程吗？搜了一下flowable的文档，居然没有扩展流程的内容，只有子流程的相关内容。你是单纯发现拖拽出扩展流程后，面板无效，还是真实业务中有使用呢？
目前还未在业务中使用，仅测试过程中发现属性面板异常，另外请问最近版的什么时候在npm发布呢？
