### ISSUE TITLE
多实例编辑有时候会出现两个 multiInstanceLoopCharacteristics 标签

### ISSUE THREAD

**Issue by xzqyun** [GoldSubmarine/workflow-bpmn-modeler#23]
多实例编辑有时候会出现两个 multiInstanceLoopCharacteristics 标签,this.element.businessObject  属性中多出了一个loopCharacteristics

这个地方要看bpmn.io库里面，这个标签到底是哪个key，究竟是loopCharacteristics还是 multiInstanceLoopCharacteristics

**Comment by GoldSubmarine** [comment]
无法复现
