### ISSUE TITLE
组件 :xml 无法刷新 

### ISSUE THREAD

**Issue by liangbaika** [GoldSubmarine/workflow-bpmn-modeler#24]
![image](https://user-images.githubusercontent.com/33059022/100069229-71c84880-2e73-11eb-885c-69b0b98c8f7a.png)
![image](https://user-images.githubusercontent.com/33059022/100069238-768cfc80-2e73-11eb-85e1-da66c9f35dff.png)
![image](https://user-images.githubusercontent.com/33059022/100069279-873d7280-2e73-11eb-8661-aac89e35c505.png)

父组件 传入一个有值的xml更新后  再次传入一个空的xml 去新增模型 可是还是显示之前的那个旧的   无法更新 xml

**Comment by GoldSubmarine** [comment]
你能通过 vuetool ，把 bpmn-modeler 这个组件 props 截图出来吗？看了代码，应该是会更新的
