### ISSUE TITLE
多实例配置问题

### ISSUE THREAD

**Issue by Rick-yi** [GoldSubmarine/workflow-bpmn-modeler#26]
![image](https://user-images.githubusercontent.com/29530775/101849361-81919d80-3b92-11eb-978d-ff1244169fad.png)
从flowable-ui导出XML文件后导入过来，多实例里的配置不展示

**Comment by GoldSubmarine** [comment]
https://github.com/GoldSubmarine/workflow-bpmn-modeler/issues/10#issuecomment-699904635

**Comment by GoldSubmarine** [comment]
一个功能可能有很多种不同的配置方法，比如多实例，flowable 文档中有 3 种配置方法，我实现了其中一种，所以其他流程器导出的xml，不一定能在我的设计器中回显数据。
