### ISSUE TITLE
CDATA中的小于号无法被解析

### ISSUE THREAD

**Issue by yugonglan** [GoldSubmarine/workflow-bpmn-modeler#27]
bpmn文件有条件表达式不能识别     导入文件含有" <conditionExpression xsi:type="tFormalExpression"><![CDATA[${amount>500}]]></conditionExpression>"出现
index.vue?6ced:159 unparsable content <=500}]]&gt;</conditionExpression> detected; this may indicate an invalid BPMN 2.0 diagram file
	line: 44
	column: 78
	nested error: illegal first char nodeName Array(6)
_callee$ @ index.vue?6ced:159

**Comment by yugonglan** [comment]
导入含有` <conditionExpression xsi:type="tFormalExpression"><![CDATA[${amount>500}]]></conditionExpression>`出现`index.vue?6ced:159 unparsable content <=500}]]&gt;</conditionExpression> detected; this may indicate an invalid BPMN 2.0 diagram file
	line: 44
	column: 78
	nested error: illegal first char nodeName Array(6)
_callee$ @ index.vue?6ced:159
`

**Comment by GoldSubmarine** [comment]
可否提供完整的 xml 文件

**Comment by yugonglan** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:flowable="http://flowable.org/bpmn" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:omgdc="http://www.omg.org/spec/DD/20100524/DC" xmlns:omgdi="http://www.omg.org/spec/DD/20100524/DI" typeLanguage="http://www.w3.org/2001/XMLSchema" expressionLanguage="http://www.w3.org/1999/XPath" targetNamespace="http://www.flowable.org/processdef">
  <process id="contract" name="合同流程" isExecutable="true">
    <documentation>为合同审批而设计</documentation>
    <startEvent id="userTask0" name="开始"></startEvent>
    <userTask id="userTask1" name="提交人" flowable:assignee="${initiator}" flowable:formKey="PM_15_11,PM_15_12" flowable:skipExpression="${initiator==''}">
      <extensionElements>
        <modeler:initiator-can-complete xmlns:modeler="http://flowable.org/modeler"><![CDATA[false]]></modeler:initiator-can-complete>
      </extensionElements>
    </userTask>
    <sequenceFlow id="sid-3725C055-BABF-49F8-BE44-B4EADCEEFC1E" sourceRef="userTask0" targetRef="userTask1"></sequenceFlow>
    <userTask id="userTask2" name="项目经理" flowable:assignee="0016" flowable:candidateGroups="G008" flowable:formKey="PM_15_11,PM_15_12">
      <extensionElements>
        <modeler:initiator-can-complete xmlns:modeler="http://flowable.org/modeler"><![CDATA[false]]></modeler:initiator-can-complete>
      </extensionElements>
    </userTask>
    <sequenceFlow id="sid-5D0BAFD5-163D-40FB-B4E2-E548F793BAEA" sourceRef="userTask1" targetRef="userTask2"></sequenceFlow>
    <userTask id="userTask3" name="部长审批" flowable:assignee="0017" flowable:candidateGroups="G006" flowable:formKey="PM_15_11,PM_15_12">
      <extensionElements>
        <modeler:initiator-can-complete xmlns:modeler="http://flowable.org/modeler"><![CDATA[false]]></modeler:initiator-can-complete>
      </extensionElements>
    </userTask>
    <sequenceFlow id="sid-598DAFDF-EF07-4CD2-BDE2-DD5B1B5B5D24" sourceRef="userTask2" targetRef="userTask3"></sequenceFlow>
    <subProcess id="subprocess1" name="财务审批子流程">
      <startEvent id="userTask4" name="开始"></startEvent>
      <userTask id="userTask5" name="财务部长助理审批" flowable:assignee="0018" flowable:candidateGroups="G009" flowable:formKey="PM_15_11,PM_15_12">
        <extensionElements>
          <modeler:initiator-can-complete xmlns:modeler="http://flowable.org/modeler"><![CDATA[false]]></modeler:initiator-can-complete>
        </extensionElements>
      </userTask>
      <exclusiveGateway id="exclusivegateway1"></exclusiveGateway>
      <userTask id="userTask6" name="财务部长审批" flowable:assignee="0019" flowable:candidateGroups="G010" flowable:formKey="PM_15_11,PM_15_12">
        <extensionElements>
          <modeler:initiator-can-complete xmlns:modeler="http://flowable.org/modeler"><![CDATA[false]]></modeler:initiator-can-complete>
        </extensionElements>
      </userTask>
      <endEvent id="userTask10" name="结束"></endEvent>
      <sequenceFlow id="sid-1BAE167F-4F62-49C4-BCF6-598BF8050ECD" sourceRef="userTask4" targetRef="userTask5"></sequenceFlow>
      <sequenceFlow id="sid-ADFEEB6C-D777-4431-BE78-973F64AF4C2D" sourceRef="userTask5" targetRef="exclusivegateway1"></sequenceFlow>
      <sequenceFlow id="sid-2C048234-D896-4AD7-91DD-878CF38F6705" sourceRef="userTask6" targetRef="userTask10"></sequenceFlow>
      <sequenceFlow id="userTask7" name="大于500w" sourceRef="exclusivegateway1" targetRef="userTask6">
        <conditionExpression xsi:type="tFormalExpression"><![CDATA[${amount>500}]]></conditionExpression>
      </sequenceFlow>
      <sequenceFlow id="userTask8" name="小于等于500w" sourceRef="exclusivegateway1" targetRef="userTask10">
        <conditionExpression xsi:type="tFormalExpression"><![CDATA[${amount<=500}]]></conditionExpression>
      </sequenceFlow>
    </subProcess>
    <sequenceFlow id="sid-FF916873-78A8-473E-9A44-8B8305A827DD" sourceRef="userTask3" targetRef="subprocess1"></sequenceFlow>
    <userTask id="userTask11" name="董事长审批" flowable:assignee="0020" flowable:candidateGroups="G011" flowable:formKey="PM_15_11,PM_15_12">
      <extensionElements>
        <modeler:initiator-can-complete xmlns:modeler="http://flowable.org/modeler"><![CDATA[false]]></modeler:initiator-can-complete>
      </extensionElements>
    </userTask>
    <sequenceFlow id="sid-5516EF88-1BA2-4CE1-830A-DD913742EC79" sourceRef="subprocess1" targetRef="userTask11"></sequenceFlow>
    <endEvent id="userTask12" name="结束"></endEvent>
    <sequenceFlow id="sid-684BE17D-65D7-4619-89D6-33B63C06E5C9" sourceRef="userTask11" targetRef="userTask12"></sequenceFlow>
  </process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_contract">
    <bpmndi:BPMNPlane bpmnElement="contract" id="BPMNPlane_contract">
      <bpmndi:BPMNShape bpmnElement="userTask0" id="BPMNShape_userTask0">
        <omgdc:Bounds height="30.0" width="30.0" x="90.00000000000004" y="75.00000000000001"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="userTask1" id="BPMNShape_userTask1">
        <omgdc:Bounds height="80.0" width="99.99999999999997" x="165.00000000000003" y="50.000000000000036"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="userTask2" id="BPMNShape_userTask2">
        <omgdc:Bounds height="79.99999999999997" width="100.0" x="345.00000000000017" y="50.00000000000002"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="userTask3" id="BPMNShape_userTask3">
        <omgdc:Bounds height="80.0" width="100.0" x="531.0000000000002" y="50.00000000000001"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="subprocess1" id="BPMNShape_subprocess1">
        <omgdc:Bounds height="217.00000000000003" width="471.99999999999994" x="345.00000000000017" y="255.00000000000003"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="userTask4" id="BPMNShape_userTask4">
        <omgdc:Bounds height="30.0" width="30.0" x="362.5555476229868" y="299.9999999999999"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="userTask5" id="BPMNShape_userTask5">
        <omgdc:Bounds height="80.0" width="100.0" x="437.55554762298686" y="274.99999999999994"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="exclusivegateway1" id="BPMNShape_exclusivegateway1">
        <omgdc:Bounds height="40.0" width="40.0" x="570.0000000000001" y="295.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="userTask6" id="BPMNShape_userTask6">
        <omgdc:Bounds height="80.0" width="100.0" x="690.0000000000001" y="274.99999999999994"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="userTask10" id="BPMNShape_userTask10">
        <omgdc:Bounds height="28.0" width="28.0" x="726.0000000000002" y="420.00000000000006"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="userTask11" id="BPMNShape_userTask11">
        <omgdc:Bounds height="80.0" width="100.0" x="870.0000000000001" y="323.5000000000001"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="userTask12" id="BPMNShape_userTask12">
        <omgdc:Bounds height="28.0" width="28.0" x="1035.0000000000002" y="349.5000000000001"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="userTask8" id="BPMNEdge_userTask8">
        <omgdi:waypoint x="601.1241081382386" y="323.8254646840149"></omgdi:waypoint>
        <omgdi:waypoint x="729.0271651640916" y="425.29858590130164"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="sid-3725C055-BABF-49F8-BE44-B4EADCEEFC1E" id="BPMNEdge_sid-3725C055-BABF-49F8-BE44-B4EADCEEFC1E">
        <omgdi:waypoint x="119.94999848995764" y="90.00000000000001"></omgdi:waypoint>
        <omgdi:waypoint x="164.99999999996044" y="90.00000000000003"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="sid-5D0BAFD5-163D-40FB-B4E2-E548F793BAEA" id="BPMNEdge_sid-5D0BAFD5-163D-40FB-B4E2-E548F793BAEA">
        <omgdi:waypoint x="264.95000000000005" y="90.0"></omgdi:waypoint>
        <omgdi:waypoint x="345.00000000000017" y="90.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="sid-5516EF88-1BA2-4CE1-830A-DD913742EC79" id="BPMNEdge_sid-5516EF88-1BA2-4CE1-830A-DD913742EC79">
        <omgdi:waypoint x="816.9499999997022" y="363.50000000000006"></omgdi:waypoint>
        <omgdi:waypoint x="870.0000000000001" y="363.5000000000001"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="sid-FF916873-78A8-473E-9A44-8B8305A827DD" id="BPMNEdge_sid-FF916873-78A8-473E-9A44-8B8305A827DD">
        <omgdi:waypoint x="581.0000000000002" y="129.95000000000002"></omgdi:waypoint>
        <omgdi:waypoint x="581.0000000000001" y="255.00000000000003"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="sid-1BAE167F-4F62-49C4-BCF6-598BF8050ECD" id="BPMNEdge_sid-1BAE167F-4F62-49C4-BCF6-598BF8050ECD">
        <omgdi:waypoint x="392.50554611300987" y="314.99999999999994"></omgdi:waypoint>
        <omgdi:waypoint x="437.55554762298686" y="314.99999999999994"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="sid-ADFEEB6C-D777-4431-BE78-973F64AF4C2D" id="BPMNEdge_sid-ADFEEB6C-D777-4431-BE78-973F64AF4C2D">
        <omgdi:waypoint x="537.5055476229869" y="315.0"></omgdi:waypoint>
        <omgdi:waypoint x="570.0000000000001" y="315.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="sid-598DAFDF-EF07-4CD2-BDE2-DD5B1B5B5D24" id="BPMNEdge_sid-598DAFDF-EF07-4CD2-BDE2-DD5B1B5B5D24">
        <omgdi:waypoint x="444.94999999994" y="90.0"></omgdi:waypoint>
        <omgdi:waypoint x="530.9999999999118" y="90.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="sid-2C048234-D896-4AD7-91DD-878CF38F6705" id="BPMNEdge_sid-2C048234-D896-4AD7-91DD-878CF38F6705">
        <omgdi:waypoint x="740.0000000000001" y="354.94999999999993"></omgdi:waypoint>
        <omgdi:waypoint x="740.0000000000002" y="420.00000000000006"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="userTask7" id="BPMNEdge_userTask7">
        <omgdi:waypoint x="609.9433544303798" y="315.0"></omgdi:waypoint>
        <omgdi:waypoint x="689.9999999998795" y="314.99999999999994"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="sid-684BE17D-65D7-4619-89D6-33B63C06E5C9" id="BPMNEdge_sid-684BE17D-65D7-4619-89D6-33B63C06E5C9">
        <omgdi:waypoint x="969.9499999999391" y="363.5000000000001"></omgdi:waypoint>
        <omgdi:waypoint x="1035.0000000000002" y="363.5000000000001"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</definitions>`

**Comment by GoldSubmarine** [comment]
[CDATA - （未解析）字符数据](https://www.runoob.com/xml/xml-cdata.html)

"<" 和 "&" 字符在 XML 元素中都是非法的，就像我们使用 mybatis 写 sql 的时候也没法用小于号，但是用 CDATA 包裹起来的文本是可以出现小于号的，所以你的 xml 写法是对的，这个地方感觉是 bpmn 的坑。

所以我准备弃用 CDATA ，直接使用转义字符，自动将 `<` 和 `&`  转换成 `&gt;` 和 `&amp;`

**Comment by yugonglan** [comment]
@GoldSubmarine 你说的是有道理,但是也要考虑实际情况,不管是activiti还是flowable,都是用CDATA,新的方向是没错,但是也要考虑之前的导出文件能适配

**Comment by GoldSubmarine** [comment]
兼容一下就可以了
