### ISSUE TITLE
多实例会多出现一个标签

### ISSUE THREAD

**Issue by yugonglan** [GoldSubmarine/workflow-bpmn-modeler#29]
`<multiInstanceLoopCharacteristics />`  总是多一个

**Comment by GoldSubmarine** [comment]
试了下，没有复现啊，麻烦提供下步骤

**Comment by yugonglan** [comment]
我设置一个节点,设置多实例,下载后打开xml文件都会有`<userTask id="Activity_1vu0ztq" name="多实例" flowable:assignee="${assign}">
      <incoming>Flow_0y6vyhs</incoming>
      <outgoing>Flow_1bi81t3</outgoing>
      <multiInstanceLoopCharacteristics />
      <multiInstanceLoopCharacteristics isSequential="false" flowable:collection="userList" flowable:elementVariable="assign">
        <completionCondition>nrOfCompletedInstances/nrOfInstances=0.6</completionCondition>
      </multiInstanceLoopCharacteristics>
    </userTask>`

**Comment by yugonglan** [comment]
我画两次导出都会有多一个`<multiInstanceLoopCharacteristics />`

**Comment by GoldSubmarine** [comment]
还是没有复现，你直接用我提供的 [github pages](https://goldsubmarine.github.io/workflow-bpmn-modeler/demo/) 页面试试，也会这样吗？

**Comment by yugonglan** [comment]
打不开,具体步骤:画一个开始节点,一个用户任务节点,设置为并行,再画一个结束节点,具体xml:`<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:omgdc="http://www.omg.org/spec/DD/20100524/DC" xmlns:bioc="http://bpmn.io/schema/bpmn/biocolor/1.0" xmlns:flowable="http://flowable.org/bpmn" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.flowable.org/processdef">
  <process id="process_ugg92cb9" name="name_rrx911b3">
    <startEvent id="startNode1" name="开始">
      <outgoing>Flow_0y6vyhs</outgoing>
    </startEvent>
    <sequenceFlow id="Flow_0y6vyhs" sourceRef="startNode1" targetRef="Activity_1vu0ztq" />
    <endEvent id="Event_0ok10xk">
      <incoming>Flow_1bi81t3</incoming>
    </endEvent>
    <sequenceFlow id="Flow_1bi81t3" sourceRef="Activity_1vu0ztq" targetRef="Event_0ok10xk" />
    <userTask id="Activity_1vu0ztq" name="多实例" flowable:assignee="${assign}">
      <incoming>Flow_0y6vyhs</incoming>
      <outgoing>Flow_1bi81t3</outgoing>
      <multiInstanceLoopCharacteristics />
      <multiInstanceLoopCharacteristics isSequential="false" flowable:collection="userList" flowable:elementVariable="assign">
        <completionCondition>nrOfCompletedInstances/nrOfInstances=0.6</completionCondition>
      </multiInstanceLoopCharacteristics>
    </userTask>
  </process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_flow">
    <bpmndi:BPMNPlane id="BPMNPlane_flow" bpmnElement="process_ugg92cb9">
      <bpmndi:BPMNEdge id="Flow_0y6vyhs_di" bpmnElement="Flow_0y6vyhs">
        <di:waypoint x="270" y="215" />
        <di:waypoint x="320" y="215" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1bi81t3_di" bpmnElement="Flow_1bi81t3">
        <di:waypoint x="420" y="215" />
        <di:waypoint x="472" y="215" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="BPMNShape_startNode1" bpmnElement="startNode1" bioc:stroke="">
        <omgdc:Bounds x="240" y="200" width="30" height="30" />
        <bpmndi:BPMNLabel>
          <omgdc:Bounds x="242" y="237" width="23" height="14" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_0ok10xk_di" bpmnElement="Event_0ok10xk">
        <omgdc:Bounds x="472" y="197" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_1rcaq05_di" bpmnElement="Activity_1vu0ztq">
        <omgdc:Bounds x="320" y="175" width="100" height="80" />
      </bpmndi:BPMNShape>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</definitions>
`

**Comment by yugonglan** [comment]
你这个地址打不开,确实会出现这个情况,我看到之前也有人提过issues

**Comment by GoldSubmarine** [comment]
地址打不开是没有翻墙。

你说的应该是 #23 ，晚上回去看看，现在 github pages 上应该是没有问题的，猜测可能是你们安装的时候，有些包自动升级了。
