### ISSUE TITLE
新建任务右侧属性栏没有“人员类型”，“表单标识”等信息

### ISSUE THREAD

**Issue by yinzi2012** [GoldSubmarine/workflow-bpmn-modeler#3]
新建任务右侧属性栏没有“人员类型”，“表单标识”等信息
原来的“用户任务”有这些信息，请问是什么问题？

**Comment by GoldSubmarine** [comment]
![image](https://user-images.githubusercontent.com/22909744/91287029-c9e2a680-e7c1-11ea-820d-145c02fdaa0a.png)

**Comment by yinzi2012** [comment]
谢谢

**Comment by GoldSubmarine** [comment]
客气 😁
