### ISSUE TITLE
流程表单怎么设置

### ISSUE THREAD

**Issue by 0703gaoxiaobo** [GoldSubmarine/workflow-bpmn-modeler#33]
如何给流程节点配置流程表单

**Comment by GoldSubmarine** [comment]
目前无法配置，但是你真的会使用流程设计器来配置表单吗？比如我实现了该功能，但我使用的是bootstrap这个css风格，而你使用的element-ui，显然这是不配套的。

目前你可以通过formKey来配置该流程节点需要打开的url地址，后端从获取到该节点的url后，返回给前端这个url，那前端根据这个路由就知道应该打开哪个页面了。如果你是jsp，直接302跳转到该地址即可

**Comment by 0703gaoxiaobo** [comment]
![image](https://user-images.githubusercontent.com/49136063/103115847-18844c80-469f-11eb-9420-ef39d196f187.png)
先设计好表单，然后去选择关联，要怎么实现

**Comment by GoldSubmarine** [comment]
这个没有研究过，我们都是用的formKey，前端自己写对应的页面，没有使用过 flowable 的 form 那块功能
