### ISSUE TITLE
信号定义报错报错

### ISSUE THREAD

**Issue by xiaosatufu** [GoldSubmarine/workflow-bpmn-modeler#34]
信号定义报错报错，源代码里面似乎没有写保存操作。另外signal标签可以和process标签在同一级吗？
生成的signal标签在xml中应该是有多个，但是在源代码里面也没看到循环赋值操作？

**Comment by GoldSubmarine** [comment]
signal标签和process标签是在同一级，目前只实现了页面，的确没有保存到xml中，其他的属性配置都是对该节点进行配置，signal并不是对该节点的描述，所以上次写了一半就没有继续

**Comment by xiaosatufu** [comment]
光速回复，👍一个！
另外可以更新一下吗，或者我这边需要怎么处理？
卡在这里了。。。不知道怎么操作了。。
我现在想新建signal标签并且给他们一些属性值

**Comment by GoldSubmarine** [comment]
印象里还是比较麻烦的，我没法预期什么时候能完成该功能，当然也要看我自己的时间安排。

没有什么好的方法可以临时解决，也许只能导出xml，手动修改xml了

**Comment by xiaosatufu** [comment]
好的吧，只有静待更新了。麻烦了。

**Comment by GoldSubmarine** [comment]
可以加个微信沟通下嘛？我的微信是：x997462392
