### ISSUE TITLE
用户任务怎么创建，设计器里面没有找到

### ISSUE THREAD

**Issue by 0703gaoxiaobo** [GoldSubmarine/workflow-bpmn-modeler#36]

**Comment by GoldSubmarine** [comment]
Duplicate of #3

**Comment by 0703gaoxiaobo** [comment]
你好，你回复的截图我看不到，能重新发一个吗

**Comment by GoldSubmarine** [comment]
应该是没有翻墙，重新发还是看不到的，`user-images.githubusercontent.com` 这个域名需要翻墙

**Comment by 0703gaoxiaobo** [comment]
添加用户任务，是先创建一个普通任务，然后导出bpmn.xml文件，然后修改为userTask，是吗

**Comment by GoldSubmarine** [comment]
拖拽出一个任务，然后点击一下那个任务，就会出现一个 **扳手** ，点击扳手，选择用户任务

**Comment by 0703gaoxiaobo** [comment]
看到了，谢谢，这个不可以默认为用户任务吗，大多数任务肯定都是需要用户参与到一起的

**Comment by GoldSubmarine** [comment]
参见 #21 ，提问前查一下以前的 issue 哈，你的这些问题都是有人问过的，如有不解，可以在别人的 issue 下继续提问
