### ISSUE TITLE
在vue中使用的问题

### ISSUE THREAD

**Issue by zhongshanhao** [GoldSubmarine/workflow-bpmn-modeler#38]
在vue中使用v-show动态隐藏modeler，在v-show控制显示时会出现画布不可用的问题，拖动会造成如下图的问题，如何解决这个问题？v-show是动态给标签增加`style="display: none;"`来控制组件显示隐藏的

![image](https://user-images.githubusercontent.com/19641047/104399742-40731b80-558c-11eb-9855-9d43e51c2194.png)

**Comment by zhongshanhao** [comment]
@GoldSubmarine 大佬帮忙看看

**Comment by GoldSubmarine** [comment]
未复现问题，可否提供一个 demo
