### ISSUE TITLE
节点设置颜色之后 deploy 流程提示color属性不支持

### ISSUE THREAD

**Issue by yc850903** [GoldSubmarine/workflow-bpmn-modeler#40]
节点设置颜色之后 deploy 流程提示color属性不支持。
报错信息如下：
org.flowable.bpmn.exceptions.XMLException: javax.xml.stream.XMLStreamException: org.xml.sax.SAXParseException; lineNumber: 5; columnNumber: 8; cvc-complex-type.3.2.2: Attribute 'color' is not allowed to appear in element 'startEvent'.

**Comment by GoldSubmarine** [comment]
flowable版本是？

**Comment by yc850903** [comment]
> flowable版本是？

6.3.0

**Comment by GoldSubmarine** [comment]
6.5.0应该是可以的

**Comment by yc850903** [comment]
> 6.5.0应该是可以的

OK谢谢！那我升级下版本。

**Comment by yc850903** [comment]
> 6.5.0应该是可以的

6.5.0 6.6.0都会报错！！

**Comment by GoldSubmarine** [comment]
感谢测试，太久不碰了，印象中这个功能是可以的，并且它也是bpmn支持的规范之一。

暂时你先别设置颜色吧，而且现在颜色设置是有问题的，文字和背景颜色区分不开，后期能直接移除这个功能，好像也没啥用😂

**Comment by yc850903** [comment]
> 感谢测试，太久不碰了，印象中这个功能是可以的，并且它也是bpmn支持的规范之一。
> 
> 暂时你先别设置颜色吧，而且现在颜色设置是有问题的，文字和背景颜色区分不开，后期能直接移除这个功能，好像也没啥用😂

这个颜色确实没什么用！！其他的功能还是不错地！

**Comment by GoldSubmarine** [comment]
已移除颜色设置
