### ISSUE TITLE
自定义节点属性，属性无法回显

### ISSUE THREAD

**Issue by tony2y** [GoldSubmarine/workflow-bpmn-modeler#43]
自己在侧边栏新增了一个input,输入值后，点击其它节点后再回来查看当前节点。之前设置的值为空了。请问有自定义属性的教程吗？这里应该是会进行保存，但就是不知道怎么操作。。（非专业前端开发）

**Comment by GoldSubmarine** [comment]
你可以网上找一下 bpmn.js 自定义属性的教程，感觉不是前端开发做起来难度还是有的。
另外，readme上其实写了，不推荐自定义属性的，可以考虑通过额外的增删改查来实现功能。
