### ISSUE TITLE
多实例节点保存错误

### ISSUE THREAD

**Issue by yugonglan** [GoldSubmarine/workflow-bpmn-modeler#45]
含有多实例节点保存后,在修改里面的多实例的元素变量或集合在保存就多出现一个   flowable:elementVariable="" 属性

**Comment by GoldSubmarine** [comment]
是否版本是？

**Comment by yugonglan** [comment]
当时最新的一次提交 在   59a2e4553bc8680b2c7858bb18fc0fa93477d9e3   ,tag在0.2.5

**Comment by GoldSubmarine** [comment]
升级到 0.2.8 试试，中间修了几次多实例问题
