### ISSUE TITLE
多实例`isSequential="false"`

### ISSUE THREAD

**Issue by yugonglan** [GoldSubmarine/workflow-bpmn-modeler#46]
多实例选择 串行 会显示`isSequential="true"` 但是 选择 并行应该 显示 `isSequential="false"`, 但是 `isSequential` 没了 ,能把  `isSequential="false"` 时 也显示吗

**Comment by GoldSubmarine** [comment]
这个影响到任务的并行执行了吗？

**Comment by yugonglan** [comment]
暂时还没发现对执行任务有影响,但是看xml,不知道这个是并行

**Comment by GoldSubmarine** [comment]
这个就是默认值，默认值不显示很正常啊

例如  html：`<button>123</button>`  

而不必写成  `<button type="button" autofocus="false" disabled="false">123</button>`
