### ISSUE TITLE
vue3考虑下呗 

### ISSUE THREAD

**Issue by duansheli** [GoldSubmarine/workflow-bpmn-modeler#47]
考虑下升级库版本呗 
bpmn js 已经 v8.7 了 
vite 开发比较轻量化

**Comment by GoldSubmarine** [comment]
库版本暂时不考虑升级，readme已经写过了，因为本项目是一个应用型项目，不是基础类库，满足当前应用需求且没有bug即可

关于 `vite`，一是不成熟，二是本项目并不大，启动速度并不慢，找不到用 `vite` 的理由，当然如果只是玩技术的话的确可以。

而且我对 `vite` 的前景有点看的不太清楚，因为它是 `vue` 作者开发的，所以 `vue` 社区很火，但是你去 `react`  issue 区看看的话，根本没有人提这个，如果它真的这么好的话，应该被广泛使用才是，当然我也不是否定它，只是持怀疑态度，而且我主要做后端开发，对前端没有进一步的研究。

感谢你的建议。
