### ISSUE TITLE
数据对象暂时无法设置其节点属性

### ISSUE THREAD

**Issue by lensun1** [GoldSubmarine/workflow-bpmn-modeler#7]

**Comment by GoldSubmarine** [comment]
好的，这两天支持下，下个版本修复

**Comment by GoldSubmarine** [comment]
看了下，虽然 bpmn 规范里有数据对象，但是 flowable 并没有这样的 activity 节点，所以计划移除数据对象

**Comment by gotounix** [comment]
@GoldSubmarine 数据存储、子流程、扩展流程、分组也不能设置属性。

**Comment by GoldSubmarine** [comment]
是的，还未适配，要适配的种类太多了，目前只实现了常用的，而且我发现flowable官方的设计器也只实现了少部分，很多功能文档里注明了xml如何配置，但是官方的设计器上却无法配置。

要实现全部的功能，工作量太大了，子流程计划支持，这个还是比较常用的

**Comment by GoldSubmarine** [comment]
常用功能都已支持
