### ISSUE TITLE
初始化流程，右边控制面板未加载，必须点击画布才能显示

### ISSUE THREAD

**Issue by lensun1** [GoldSubmarine/workflow-bpmn-modeler#8]

**Comment by teamemory** [comment]
你好，这个需要大概是实现思路有没？ 我监听如下事件，发现获取到的element内容不对。

![image](https://user-images.githubusercontent.com/24648667/96223707-ef6d7e80-0fc0-11eb-8bdf-db3a71221de7.png)

**Comment by GoldSubmarine** [comment]
这个还没有看过，但是应该不影响使用吧

**Comment by teamemory** [comment]
> 这个还没有看过，但是应该不影响使用吧

哈哈，一进来不美观，想着弄一下

**Comment by GoldSubmarine** [comment]
欢迎pr

**Comment by teamemory** [comment]
已解决：
步骤1：
PropertyPanel.vue 中 增加

this.modeler.on("root.added", (e) => {
        let element = e.element;
        if (element.id === "__implicitroot") {
          return;
        }
        this.element = element;
      });
![image](https://user-images.githubusercontent.com/24648667/96326902-36ae4a80-1067-11eb-829f-558b34c6bb40.png)

步骤2：
init.js 中id改为 __implicitroot
<process id="__implicitroot" name="name_${randomStr()}">
![image](https://user-images.githubusercontent.com/24648667/96326904-3d3cc200-1067-11eb-8f79-6d39205ce578.png)

**Comment by GoldSubmarine** [comment]
大体思路可以，不过这个xml中的process的id属性不能为固定值，每个流程的id需要是不同的，明天我试着实现下

**Comment by teamemory** [comment]
> 大体思路可以，不过这个xml中的process的id属性不能为固定值，每个流程的id需要是不同的，明天我试着实现下

好的
