### ISSUE TITLE
升级新版本问题

### ISSUE THREAD

**Issue by lensun1** [GoldSubmarine/workflow-bpmn-modeler#9]
![image](https://user-images.githubusercontent.com/25600529/92195141-dd1b0380-ee9e-11ea-9d8b-3ca9a8fdd365.png)

**Comment by GoldSubmarine** [comment]
原因是你当前的 babel 版本不支持 optional chain 语法

你可以尝试升级 babel-core 至 7.0 以上

如果你不想升级，可以安装 [@babel/plugin-proposal-optional-chaining](https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining) ，并加入到 plugin 中： `"plugins": ["@babel/plugin-proposal-optional-chaining"]`

**Comment by lensun1** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "GoldSubmarine"<notifications@github.com&gt;; 
发送时间: 2020年9月4日(星期五) 中午11:20
收件人: "GoldSubmarine/workflow-bpmn-modeler"<workflow-bpmn-modeler@noreply.github.com&gt;; 
抄送: "Len"<sldodo@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [GoldSubmarine/workflow-bpmn-modeler] 升级新版本问题 (#9)





 
原因是你当前的 babel 版本不支持 optional chain 语法
 
你可以尝试升级 babel-core 至 7.0 以上
 
如果你不想升级，可以安装 @babel/plugin-proposal-optional-chaining ，并加入到 plugin 中： "plugins": ["@babel/plugin-proposal-optional-chaining"]

**Comment by GoldSubmarine** [comment]
问题是否解决？没啥问题就关了啊

**Comment by lensun1** [comment]
按照这样加过还是不行，我参照你的packjson，也是不行




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GoldSubmarine/workflow-bpmn-modeler"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月4日(星期五) 中午11:20
收件人:&nbsp;"GoldSubmarine/workflow-bpmn-modeler"<workflow-bpmn-modeler@noreply.github.com&gt;;
抄送:&nbsp;"Len"<sldodo@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [GoldSubmarine/workflow-bpmn-modeler] 升级新版本问题 (#9)





 
原因是你当前的 babel 版本不支持 optional chain 语法
 
你可以尝试升级 babel-core 至 7.0 以上
 
如果你不想升级，可以安装 @babel/plugin-proposal-optional-chaining ，并加入到 plugin 中： "plugins": ["@babel/plugin-proposal-optional-chaining"]

**Comment by lensun1** [comment]
你有qq么，可以线上沟通一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Len"                                                                                    <sldodo@qq.com&gt;;
发送时间:&nbsp;2020年9月12日(星期六) 下午2:13
收件人:&nbsp;"GoldSubmarine/workflow-bpmn-modeler"<reply@reply.github.com&gt;;

主题:&nbsp;回复： [GoldSubmarine/workflow-bpmn-modeler] 升级新版本问题 (#9)



按照这样加过还是不行，我参照你的packjson，也是不行




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "GoldSubmarine/workflow-bpmn-modeler"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月4日(星期五) 中午11:20
收件人:&nbsp;"GoldSubmarine/workflow-bpmn-modeler"<workflow-bpmn-modeler@noreply.github.com&gt;;
抄送:&nbsp;"Len"<sldodo@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [GoldSubmarine/workflow-bpmn-modeler] 升级新版本问题 (#9)





 
原因是你当前的 babel 版本不支持 optional chain 语法
 
你可以尝试升级 babel-core 至 7.0 以上
 
如果你不想升级，可以安装 @babel/plugin-proposal-optional-chaining ，并加入到 plugin 中： "plugins": ["@babel/plugin-proposal-optional-chaining"]

**Comment by GoldSubmarine** [comment]
wechat: x997462392

**Comment by GoldSubmarine** [comment]
v0.2.2 已转换为 es5 后发布
